apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-service
  labels:
    app: hello-world-app
spec:
  selector:
    app: hello-world-app
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 5000
    nodePort: {{ .Values.service.nodePort }}
